version: '3.8'

services:
  senai-compose-postgres:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "ub_natts"
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - natts-postgres-storage:/var/lib/postgresql/data
    networks:
      - senai-compose-network

  senai-compose-webapp:
    image: webapp:1.0.0
    environment:
      DBUSER: "postgres"
      DBPASSWORD: "postgres"
      DBNAME: "ub_natts"
      DBHOST: "senai-compose-postgres"
      SECRETKEY: "e182c9c42f3c11ebadc10242ac120002"
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - senai-compose-postgres
      - senai-compose-novus
      - senai-compose-reader
    networks:
      - senai-compose-network
  senai-compose-novus:
    image: novus:1.0.0
    environment:
      DBUSER: "postgres"
      DBPASSWORD: "postgres"
      DBNAME: "ub_natts"
      DBHOST: "senai-compose-postgres"
    restart: unless-stopped
    networks:
      - senai-compose-network
    depends_on:
      - senai-compose-postgres
  senai-compose-reader:
    image: reader:1.0.0
    environment:
      DBUSER: "postgres"
      DBPASSWORD: "postgres"
      DBNAME: "ub_natts"
      DBHOST: "senai-compose-postgres"
    restart: unless-stopped
    networks:
      - senai-compose-network
    depends_on:
      - senai-compose-postgres

networks:
  senai-compose-network:
    driver: bridge

volumes:
  #change for TRUE when volume are already created
  natts-postgres-storage:
    external: true
